//created on: 2020-05-02
package com.sample.rules

import com.sample.model.InsurancePrice;
import com.sample.model.Policyholder;

rule "Pricing depends on the model: 1 - CATEGORY (most dangerous)"

    when
       i: InsurancePrice ()
       p: Policyholder(p.getCar.modelName.equals("Audi") || p.getCar.modelName.equals("BMW") )
    then
        i.price = 500.00;

end

rule "Pricing depends on the model:  2 - CATEGORY (medium dangerous)"

    when
       i: InsurancePrice ()
       p: Policyholder(p.getCar.modelName.equals("Mercedes") || p.getCar.modelName.equals("Honda") )
    then
        i.price = 400.00;

end

rule "Pricing depends on the model: 3 - CATEGORY (least dangerous)"

    when
       i: InsurancePrice ()
       p: Policyholder(p.getCar.modelName.equals("Nissan") || p.getCar.modelName.equals("Ford") )
    then
        i.price = 300.00;

end

rule "Percent calculating depends by production year: before 2000"
    when
       i: InsurancePrice ()
       p: Policyholder(p.getCar.productionYear <= 2000 )
    then
        i.price =  i.price * 1.05;

end

rule "Percent calculating depends by production year: between 2000 and 2010"
    when
       i: InsurancePrice ()
       p: Policyholder(p.getCar.productionYear > 2000 && p.getCar.productionYear <= 2010 )
    then
        i.price =  i.price * 1.07;

end

rule "Percent calculating depends by production year: between 2010 and 2020"
    when
       i: InsurancePrice ()
       p: Policyholder(p.getCar.productionYear > 2010 && p.getCar.productionYear <= 2020 )
    then
        i.price =  i.price * 1.09;

end


rule "Percent calculating depends by engine power: less than 1.0 liter"
    when
       i: InsurancePrice ()
       p: Policyholder(p.getCar.enginePower < 1.0 )
    then
        i.price =  i.price * 1.02;

end

rule "Percent calculating depends by engine power: between 1.00 and 2.5 liter"
    when
       i: InsurancePrice ()
       p: Policyholder(p.getCar.enginePower >= 1.0 && p.getCar.enginePower < 2.5 )
    then
        i.price =  i.price * 1.22;

end

rule "Percent calculating depends by engine power: between 2.5 or less liter"
    when
       i: InsurancePrice ()
       p: Policyholder(p.getCar.enginePower >= 2.5  )
    then
        i.price =  i.price * 1.52;

end

rule "Percent calculating depends by milage: less than 50 000 kilometers"
    when
       i: InsurancePrice ()
       p: Policyholder(p.getCar.mileage  < 50000  )
    then
        i.price =  i.price * 1.05;

end

rule "Percent calculating depends by milage: greater than 50 000 kilometers"
    when
       i: InsurancePrice ()
       p: Policyholder(p.getCar.mileage  >= 50000  )
    then
        i.price =  i.price * 1.15;

end

rule "Pricing depends on the fuelType:  1 - CATEGORY (PB + LPG)"

    when
       i: InsurancePrice ()
       p: Policyholder(p.getCar.fuelType.equals("LPG") || p.getCar.fuelType.equals("PB+LPG") )
    then
        i.price = i.price + 50;

end

rule "Pricing depends on the fuelType:  2 - CATEGORY (PB)"

    when
       i: InsurancePrice ()
       p: Policyholder(p.getCar.fuelType.equals("PB"))
    then
        i.price = i.price + 30;

end

rule "Pricing depends on the fuelType:  3 - CATEGORY (ON)"

    when
       i: InsurancePrice ()
       p: Policyholder(p.getCar.fuelType.equals("ON"))
    then
        i.price = i.price + 20;

end

rule "Pricing depends on the number of owners, 2 or more"

    when
       i: InsurancePrice ()
       p: Policyholder(p.getCar.numberOfOwner >= 2 )
    then
        i.price = i.price * 1.05;

end

rule "Pricing depends on the gender, female pays less"

    when
       i: InsurancePrice ()
       p: Policyholder(p.getPerson.gender.equals("female"))
    then
        i.price = i.price + 50;

end

rule "Pricing depends on the gender, female pays more"

    when
       i: InsurancePrice ()
       p: Policyholder(p.getPerson.gender.equals("female"))
    then
        i.price = i.price + 100;

end

rule "Pricing depends on the having children, Person who have kids pays with discount"

   when
       i: InsurancePrice ()
       p: Policyholder(p.getPerson.hasKids)
    then
        i.price = i.price * 0.9;

end

rule "Percent calculating depends by policyholder age: between 18 and 25 year old"
    when
       i: InsurancePrice ()
       p: Policyholder(p.getPerson.age >= 18 && p.getPerson.age < 25 )
    then
        i.price =  i.price * 1.70;

end

rule "Percent calculating depends by policyholder age: between 25 and 35 year old"
    when
       i: InsurancePrice ()
       p: Policyholder(p.getPerson.age >= 25 && p.getPerson.age < 35 )
    then
        i.price =  i.price * 1.25;

end

rule "Percent calculating depends by policyholder age: between 35 and 55 year old"
    when
       i: InsurancePrice ()
       p: Policyholder(p.getPerson.age >= 35 && p.getPerson.age < 55 )
    then
        i.price =  i.price * 1.15;

end

rule "Pricing depends on the having cullet"

   when
       i: InsurancePrice ()
       p: Policyholder(p.getDriveInfo.IsCullet)
    then
        i.price = i.price * 1.1;

end

rule "Pricing depends on the date of get drive licence: people who have less than 7 years of experience pay more"

   when
       i: InsurancePrice ()
       p: Policyholder(p.getDriveInfo().dateInYearsfromToday < 7 )
    then
        i.price = i.price * 1.1;

end

